import { headers } from 'next/headers'
import ContextProvider from '@/context'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: {
    icon: '/logo/circle.svg',
  },
}

export default async function RootLayout({ children }) {
  const headersList = await headers()
  const cookies = headersList.get('cookie')

  return (
    <html lang="en">
      <body className="min-h-full flex flex-col">
        <ContextProvider cookies={cookies}>
          {children}
        </ContextProvider>
      </body>
    </html>
  )
}
